apiVersion: apps/v1
kind: Deployment
metadata:
  name: workon-deployment
spec:
  selector:
    matchLabels:
      app: workon
  replicas: 2
  template:
    metadata:
      labels:
        app: workon
    spec:
      containers:
      - name: workon
        # image: nginx
        image: rfahham/workon:2.0.0
        # command: ["sleep", "infinity"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workon
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: workon